### ISSUE TITLE
Modifiers on graphQL interface not working

### ISSUE THREAD

**Issue by L-Botero** [johnymontana/willow-grandstack#19]
Hello,

I've had some issues following the tutorial I wanted to make you aware of including the solutions that I found. I still have an issue with the graphQL interface not accepting the options and modifiers such as "first: 10", filter, etc.

To show I am able to fetch data:
![image](https://user-images.githubusercontent.com/70966774/124620453-74e2d880-de47-11eb-9f97-24628d50cf3f.png)

but if I try a filter:
![image](https://user-images.githubusercontent.com/70966774/124620634-9f349600-de47-11eb-9171-729124eb2263.png)

full code of error:
{
  "error": {
    "errors": [
      {
        "message": "Unknown argument \"first\" on field \"Query.properties\".",
        "locations": [
          {
            "line": 2,
            "column": 14
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Unknown argument \"first\" on field \"Query.properties\".",
              "    at Object.Argument (C:\\Users\\boter\\code\\willow\\node_modules\\graphql\\validation\\rules\\KnownArgumentNamesRule.js:46:29)",
              "    at Object.enter (C:\\Users\\boter\\code\\willow\\node_modules\\graphql\\language\\visitor.js:323:29)",
              "    at Object.enter (C:\\Users\\boter\\code\\willow\\node_modules\\graphql\\utilities\\TypeInfo.js:370:25)",
              "    at visit (C:\\Users\\boter\\code\\willow\\node_modules\\graphql\\language\\visitor.js:243:26)",
              "    at Object.validate (C:\\Users\\boter\\code\\willow\\node_modules\\graphql\\validation\\validate.js:69:24)",
              "    at validate (C:\\Users\\boter\\code\\willow\\api\\node_modules\\apollo-server-core\\src\\requestPipeline.ts:536:14)",
              "    at Object.<anonymous> (C:\\Users\\boter\\code\\willow\\api\\node_modules\\apollo-server-core\\src\\requestPipeline.ts:302:32)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (C:\\Users\\boter\\code\\willow\\api\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:5:58)",
              "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
            ]
          }
        }
      }
    ]
  }
}

Another issue I encounter but I managed to fix (just for your reference):
**The error:**
if I create a db  version 3.5.18, graphQL throws an error saying that the db does not support multiple dbs and for some reason it just does not work. 

**The fix:**
I upgraded to the latest version (4.3.2 at this time) and named the db "neo4j"

**Comment by SuperSuperDev** [comment]
Just in case anyone else has this issue with pulling the first x posts, try: 

```js

{
properties (options: { limit: 1 }) {
    id
   }
}
```

**Comment by HOKINGLOK** [comment]
For those who have the same problem, may try this:
`{
properties (where:{TotalAcres_GT: 10}, 
  					options:{sort:[{TotalValue: DESC}], limit:10})
  {
  id
  AddressL_1
  AddressLin
  Assessment
  TotalValue
  TotalAcres
   }
}`

**Comment by HOKINGLOK** [comment]
For those who have the same issue, may try this:
```
{
properties (where:{TotalAcres_GT: 10},
  		  options:{sort:[{TotalValue: DESC}], limit:10})
  {
  id
  AddressL_1
  AddressLin
  Assessment
  TotalValue
  TotalAcres
   }
}
```
